"""
Django settings for swachh_manch project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys
from decouple import config
from unipath import Path
from mongoengine import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = Path(__file__).parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

APP_ENV = config('APP_ENV', default='production')
APP_NAME = config('APP_NAME', default='Swachh Munch')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('APP_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('APP_DEBUG', default=True)

ALLOWED_HOSTS = []


# Application definition

DJANGO_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

THIRD_PARTY_APPS = (
    'django_mongoengine',
    'rest_framework',
    'rest_framework_mongoengine',
)

LOCAL_APPS = (
    'events',
)

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # custom ones
    'events.middleware.AuthGateway'
]

ROOT_URLCONF = 'swachh_manch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'swachh_manch.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# MongoDB settings
MONGODB_DATABASES = {
    "default": {
        "name": config('MONGO_DB_DATABASE', default='swachh_manch_django'),
        "host": config('MONGO_DB_HOST', default='localhost'),
        "password": config('MONGO_DB_PASSWORD', default=''),
        "username": config('MONGO_DB_USERNAME', default=''),
        "tz_aware": True, # if you using timezones in django (USE_TZ = True),
    },
}

# Set sqlite to run tests

if 'test' in sys.argv:
    MONGODB_DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': PROJECT_DIR.parent.child('db.sqlite3'),
    }


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = config('APP_LOCALE', default='en-us')

TIME_ZONE = config('APP_TIME_ZONE', default='Asia/Kolkata')

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Micro service communication
AUTH_API_GATEWAY_URL=config('AUTH_API_GATEWAY_URL', 'http://auth.ichangemycity.com/')
PROFILE_API_GATEWAY_URL=config('PROFILE_API_GATEWAY_URL', 'http://profile.ichangemycity.com/')
LOCATION_API_GATEWAY_URL=config('LOCATION_API_GATEWAY_URL', 'http://locations.ichangemycity.com/')
